server:
  port: 8082
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zomato

  application:
    name: LoginRegistration
 


eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
   
data: 
 exception:
    msg: User Already Exists.
    pwdValidationMsg: Length of the password is too short, minimum length should be 8 character.   
  
 main:
    allow-circular-references: true
 mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
logging:
  file:
    path: /my-logs/app.log
    name: log.txt 
      