  
server:
  port: 8704
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zomato


      
data: 
 exception:
    msg: User Already Exists.
    pwdValidationMsg: Length of the password is too short, minimum length should be 8 character.
    
    
application:
    name: Restaurant
    
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/ 