server:
  port: 8083
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zomato

  application:
    name: RestaurantMenu


eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
      
      
logging:
  file:
    path: /my-logs/app.log
    name: log.txt 
      
data: 
 exception:
    msg: User Already Exists.
    pwdValidationMsg: Length of the password is too short, minimum length should be 8 character.  