server:
  port: 8085
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zomato

  application:
    name: PaymentService


eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/

logging:
  file:
    path: /my-logs/app.log
    name: log.txt  
      