server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: LoginRegistration
          uri: http://localhost:8082/
          predicates:
            - Path=/api/r1/**
        - id: Restaurant
          uri: http://localhost:8089/
          predicates:
            - Path=/api/r1/**
        - id: OrderService
          uri: http://localhost:8084/
          predicates:
            - Path=/api/r1/**
        - id: Payment
          uri: http://localhost:8085/
          predicates:
            - Path=/api/r1/**
        
         
         
  application:
    name: APIGateway
      
      
logging:
  file:
    path: /my-logs/app.log
    name: log.txt 